amplify: "https://cdn.svgporn.com/logos/aws-amplify.svg"
android: "https://cdn.svgporn.com/logos/android-icon.svg"
angular: "https://cdn.svgporn.com/logos/angular-icon.svg"
ansible: "https://cdn.svgporn.com/logos/ansible.svg"
apache: "https://cdn.svgporn.com/logos/apache.svg"
apple: "https://cdn.svgporn.com/logos/apple.svg"
archlinux: "https://cdn.svgporn.com/logos/archlinux.svg"
aws: "https://cdn.svgporn.com/logos/aws.svg"
bash: "https://cdn.svgporn.com/logos/bash-icon.svg"
c: "https://cdn.svgporn.com/logos/c.svg"
chef: "https://cdn.svgporn.com/logos/chef.svg"
cpp: "https://cdn.svgporn.com/logos/c-plusplus.svg"
centos: "https://cdn.svgporn.com/logos/centos-icon.svg"
clion: "https://cdn.svgporn.com/logos/clion.svg"
csharp: "https://cdn.svgporn.com/logos/c-sharp.svg"
debian: "https://cdn.svgporn.com/logos/debian.svg"
discord: "https://cdn.svgporn.com/logos/discord-icon.svg"
docker: "https://cdn.svgporn.com/logos/docker-icon.svg"
dynamo: "https://cdn.svgporn.com/logos/aws-dynamodb.svg"
electron: "https://cdn.svgporn.com/logos/electron.svg"
fedora: "https://cdn.svgporn.com/logos/fedora.svg"
freebsd: "https://cdn.svgporn.com/logos/freebsd.svg"
git: "https://cdn.svgporn.com/logos/git-icon.svg"
github: "https://cdn.svgporn.com/logos/github-icon.svg"
gitter: "https://cdn.svgporn.com/logos/gitter.svg"
gnome: "https://cdn.svgporn.com/logos/gnome-icon.svg"
gnu: "https://cdn.svgporn.com/logos/gnu.svg"
go: "https://cdn.svgporn.com/logos/go.svg"
google_devs: "https://cdn.svgporn.com/logos/google-developers.svg"
gradle: "https://cdn.svgporn.com/logos/gradle.svg"
grafana: "https://cdn.svgporn.com/logos/grafana.svg"
gulp: "https://cdn.svgporn.com/logos/gulp.svg"
homebrew: "https://cdn.svgporn.com/logos/homebrew.svg"
idea: "https://cdn.svgporn.com/logos/intellij-idea.svg"
java: "https://cdn.svgporn.com/logos/java.svg"
javascript: "https://cdn.svgporn.com/logos/javascript.svg"
jenkins: "https://cdn.svgporn.com/logos/jenkins.svg"
jwt: "https://cdn.svgporn.com/logos/jwt-icon.svg"
kafka: "https://cdn.svgporn.com/logos/kafka-icon.svg"
kde: "https://cdn.svgporn.com/logos/kde.svg"
kubernetes: "https://cdn.svgporn.com/logos/kubernetes.svg"
linkedin: "https://cdn.svgporn.com/logos/linkedin-icon.svg"
linode: "https://cdn.svgporn.com/logos/linode.svg"
linux_mint: "https://cdn.svgporn.com/logos/linux-mint.svg"
logstash: "https://cdn.svgporn.com/logos/logstash.svg"
manjaro: "https://cdn.svgporn.com/logos/manjaro.svg"
mastadon: "https://cdn.svgporn.com/logos/mastodon-icon.svg"
mocha: "https://cdn.svgporn.com/logos/mocha.svg"
mysql: "https://cdn.svgporn.com/logos/mysql-icon.svg"
nginx: "https://cdn.svgporn.com/logos/nginx.svg"
nodejs: "https://cdn.svgporn.com/logos/nodejs-icon.svg"
nodeos: "https://cdn.svgporn.com/logos/nodeos.svg"
npm: "https://cdn.svgporn.com/logos/npm-icon.svg"
packer: "https://cdn.svgporn.com/logos/packer.svg"
postgres: "https://cdn.svgporn.com/logos/postgresql.svg"
postman: "https://cdn.svgporn.com/logos/postman-icon.svg"
puppeteer: "https://cdn.svgporn.com/logos/puppeteer.svg"
raspberry_pi: "https://cdn.svgporn.com/logos/raspberry-pi.svg"
react: "https://cdn.svgporn.com/logos/react.svg"
redis: "https://cdn.svgporn.com/logos/redis.svg"
reddit: "https://cdn.svgporn.com/logos/reddit-icon.svg"
redhat: "https://cdn.svgporn.com/logos/redhat-icon.svg"
ruby: "https://cdn.svgporn.com/logos/ruby.svg"
rubymine: "https://cdn.svgporn.com/logos/rubymine.svg"
rust: "https://cdn.svgporn.com/logos/rust.svg"
slack: "https://cdn.svgporn.com/logos/slack-icon.svg"
stackoverflow: "https://cdn.svgporn.com/logos/stackoverflow-icon.svg"
svelte: "https://cdn.svgporn.com/logos/svelte-icon.svg"
swagger: "https://cdn.svgporn.com/logos/swagger.svg"
targetprocess: "https://cdn.svgporn.com/logos/targetprocess.svg"
tensorflow: "https://cdn.svgporn.com/logos/tensorflow.svg"
terraform: "https://cdn.svgporn.com/logos/terraform-icon.svg"
travis_ci: "https://cdn.svgporn.com/logos/travis-ci.svg"
typescript: "https://cdn.svgporn.com/logos/typescript-icon.svg"
tux: "https://cdn.svgporn.com/logos/linux-tux.svg"
twilio: "https://cdn.svgporn.com/logos/twilio-icon.svg"
ubuntu: "https://cdn.svgporn.com/logos/ubuntu.svg"
vim: "https://cdn.svgporn.com/logos/vim.svg"
vuejs: "https://cdn.svgporn.com/logos/vue.svg"
vuetify: "https://cdn.svgporn.com/logos/vuetifyjs.svg"
webstorm: "https://cdn.svgporn.com/logos/webstorm.svg"
