version: 2.1

orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.8.3

jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - run: git config --global user.email "noahtkeller+gh-deploy@gmail.com"
      - run: git config --global user.name "GitHub Deployer"
      - add_ssh_keys:
          fingerprints:
            - 86:ae:c5:92:80:ed:39:c7:75:83:dc:0f:10:de:c0:d6
      - checkout
      - run: git subtree split --prefix src -b sources ${CIRCLE_BRANCH}
      - run: git push ssh://git@github.com/noahtkeller/node-common-strings.git sources
      - run: |
          curl --request POST \
          -u ${API_TOKEN}: \
          --url https://circleci.com/api/v2/project/github/noahtkeller/node-common-strings/pipeline \
          --header "Content-Type: application/json" \
          -d "{\"branch\":\"${CIRCLE_BRANCH}\",\"parameters\":{\"msg\":\"$(git rev-parse sources)\"}}"

workflows:
  on_commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
